export const INIT_TAGS = [
  { id: 1, name: 'Lập trình' },
  { id: 2, name: 'Thiết kế đồ họa' },
  { id: 3, name: 'Tình nguyện' },
  { id: 4, name: 'Thể thao' },
  { id: 5, name: 'Âm nhạc' },
  { id: 6, name: 'Vẽ tranh' },
  { id: 7, name: 'Khoa học' },
  { id: 8, name: 'Tiếng Anh' },
  { id: 9, name: 'Kinh doanh' },
  { id: 10, name: 'Lãnh đạo' },
  { id: 11, name: 'Giao tiếp' },
  { id: 12, name: 'Kỹ năng mềm' },
  { id: 13, name: 'Văn hóa' },
  { id: 14, name: 'Khiêu vũ' },
  { id: 15, name: 'Ngoại ngữ' },
  { id: 16, name: 'Công nghệ' },
  { id: 17, name: 'Sáng tạo' },
  { id: 18, name: 'Tập thể' },
  { id: 19, name: 'Chương trình' },
  { id: 20, name: 'Hội nhập' },
];
