export const INIT_UNITS = [
  {
    id: 1,
    name: 'Liên Chi Hội Sinh Viên Cần Thơ',
    type: 'LCH' as const,
    code: 'LCHSVCT',
    description: 'Liên Chi Hội Sinh Viên Cần Thơ',
    parentId: null,
  },
  {
    id: 2,
    name: 'Chi hội sinh viên Tân Hoà',
    type: 'CH' as const,
    code: 'CH_TAN_HOA',
    description: 'Chi hội sinh viên Tân Hoà',
    parentId: 1,
  },
  {
    id: 3,
    name: 'CHI HỘI SINH VIÊN BÌNH THUỶ',
    type: 'CH' as const,
    code: 'CH_BINH_THUY',
    description: 'Chi hội sinh viên Bình Thuỷ',
    parentId: 1,
  },
  {
    id: 4,
    name: 'CHI HỘI SINH VIÊN CÁI RĂNG',
    type: 'CH' as const,
    code: 'CH_CAI_RANG',
    description: 'Chi hội sinh viên Cái Răng',
    parentId: 1,
  },
  {
    id: 5,
    name: 'CHI HỘI SINH VIÊN KẾ SÁCH',
    type: 'CH' as const,
    code: 'CH_KE_SACH',
    description: 'Chi hội sinh viên Kế Sách',
    parentId: 1,
  },
  {
    id: 6,
    name: 'CHI HỘI SINH VIÊN MỸ XUYÊN - TRẦN ĐỀ',
    type: 'CH' as const,
    code: 'CH_MY_XUYEN_TRAN_DE',
    description: 'Chi hội sinh viên Mỹ Xuyên - Trần Đề',
    parentId: 1,
  },
];
